jondot/awesome-devenv

- README.md
+ Added Shell
+ Fixed IntelliJ's broken link
> Add Shell, fix IntelliJ link

- README.md
* Add git-tools
* Add awesome-github link
* Add git-it-on
* Add git-extra-commands
* Add link to spf13 Vim configuration
* Make blank lines between sections consistent
* Remove trailing spaces
* Sort git subsection per contributing.md
> Add git tools, vim config

- README.md
Add git gutter and emmet sublime 3 plugins which are awesome
> Add gitgutter and emmet plugins

- README.md
Forgot to add the plugin list I maintain - kind of embarrassing.
> Add awesome-zsh-plugins to shell section.

- README.md
Also strip trailing whitespace
> Add Git Gutter Sublime Text 2/3 plugin

- README.md
It's basically everything you need to get started with zsh & zgen (which can load oh-my-zsh plugins and themes, only it starts new sessions faster).
> Add a link to my zsh-quickstart-kit.

- README.md
> Add more presentation frameworks and dotfiles

- README.md
A plugin to make semantic versioning and change log management easier
> Added git-semver

- README.md
Example:
```
curl 'https://api.github.com/repos/jondot/awesome-devenv/commits?per_page=5' | jq '.[] | {message: .commit.message, name: .commit.committer.name}'
```
> Add jq command line utility

- README.md
Pipe Viewer is a useful terminal utility to visualise how data is passing through a sequence of piped processes.
> Add Pipe Viewer to terminal utilities

- README.md
Hi -- I added Zappr (https://github.com/zalando/zappr), a free/open-source GitHub integration for removing bottlenecks around pull request approval and helping project owners to halt "rogue" pull requests before they're merged into the master branch
> Added Zappr to "Workflow" section

- README.md
* Added **Orchestration** section to list tools which helps to easily create complex development environments
* Added [**azk**](http://github.com/azukiapp/azk), an awesome lightweight open source orchestration tool
> Add Orchestration section

- README.md
tig is a command line tool for working with git repositories. Here's an example:
> Add tig to Git

- README.md
> Sublime Text 3 link fixed

- README.md
José Luis Antúnez's WebSlides html presentation kit pushed into the list of presentations.
> add webslides into presentation

- README.md
Completor is one of the easiest (and powerful) ways to have autocomplete in Vim.
> Add async completion framework for Vim

- README.md
Adding Mockoon as discussed in #51 
Thanks :)
> Added Mockoon

- README.md
This application allows developers to rapidly create/delete static web servers in a visual manner or from a CLI/API. It also has push button SSH sharing, similar to ngrok, allowing users to temporarily share their work-in-progress with collaborators in remote locations. It has 80K users, with a consistent growth rate of 1200-1500 new downloads each month.
> Add Fenix Web Server

- README.md
rg is really super fast specially when working with large code repository.
> Add ripgrep

- README.md
Prodmodel is a build system for data science pipelines. It versions your code and data speeding up the development and productionizing of data science pipelines and models.
https://github.com/prodmodel/prodmodel
> Add Prodmodel

- README.md
Another two places with links to hss
> fix dead links
